### PR TITLE
Use ARN resolver on assumeRoleArn.

### PR DESCRIPTION
**Pull request by derrickburns**
Addresses #271

### CODE REVIEW

**Comment by cyrus-mc** [comment]
@derrickburns 

Great PR. I was just about to do this myself but once again the community has already provided. I built and tested and it works great.

**Comment by derrickburns** [comment]
Cool!  I need to actually use it.  Any ETA on a release with it?

**Comment by Joseph-Irving** [comment]
Hi, thanks for this!

The test are failing with 
```
# github.com/uswitch/kiam/pkg/server
pkg/server/server.go:113:22: undefined: v1
pkg/server/server.go:120:22: undefined: v1
pkg/server/server.go:307:12: undefined: v1
```

**Comment by derrickburns** [comment]
I submitted a new PR. I ran the tests. They pass.

**Pull request closed without merging**
