### PR TITLE
docs: interface as kube-bridge for kube-router

### PR DESCRIPTION
**Pull request by tasdikrahman**
closes https://github.com/uswitch/kiam/issues/67

### CODE REVIEW

**Comment by pingles** [comment]
Hi @tasdikrahman,

Thanks for adding this. Would you mind adding the interfaces to the README also (there's a section titled "Typical CNI Names"). If you could it'd also be great to add comments to the deployment manifests with the other interface name examples (as listed in the same README section).

Thanks!

**Comment by tasdikrahman** [comment]
@pingles 

> Thanks for adding this. Would you mind adding the interfaces to the README also (there's a section titled "Typical CNI Names"). 

Have added it on the main README.md

>  If you could it'd also be great to add comments to the deployment manifests with the other interface name examples (as listed in the same README section).

I added it as a comment on the agent deploy manifest, would you like me to add it as a doc somewhere else? Sorry, if I got the question wrong.

**Comment by roffe** [comment]
This PR can be closed, Necessary docs for kube-router is merged by https://github.com/uswitch/kiam/pull/79 

Thanks @tasdikrahman for initial PR & thanks @pingles for awesome work :)

**Comment by pingles** [comment]
Sorry, forgot this pull was open also.

Thanks @tasdikrahman and @roffe

**Pull request closed without merging**
