### PR TITLE
setup cache TTL to be 5 minutes before the session expires

### PR DESCRIPTION
**Pull request by sp-joseluis-ledesma**
This will set the cacheTTL to sessionDuration - 5 minutes. For the default values Kiam will have the very same behavior, but right now if you increase the sessionDuration the cache is expired after 10 minutes anyway. Solves #44

### CODE REVIEW

**Comment by sp-joseluis-ledesma** [comment]
I don't know if you may prefer a configurable parameter, but I thought it may make sense to just use sessionDuration - 5 minutes

**Comment by pingles** [comment]
Thanks for more contributions :)

I can't remember whether Kiam checks this already but it would be good to make sure that the session duration value is validated to be at least 15 minutes. Likewise, the default of `duration - 5*time.Minute` feels reasonable.

**Comment by pingles** [comment]
So we don't currently validate but it would be nice if we did :)

Would you mind adding something to the server's main to validate the `session-duration` arg. We can probably just validate the duration is at least 15 minutes inside the server's main, logging a fatal if it's too short.

**Comment by pingles** [comment]
Actually- we should probably place that const into the `sts` package and reference from the server cmd, so it'd be something like `sts.AWSMinSessionDuration`?

**Comment by sp-joseluis-ledesma** [comment]
It makes sense. PR updated

**Comment by pingles** [comment]
Thanks @sp-joseluis-ledesma

**Pull request merged**
