### PR TITLE
Helm chart v4 release compatibility

### PR DESCRIPTION
**Pull request by stefansedich**
This PR makes the changes required to the chart for full compatiblity with the v4 release, to be merged at or post ther v4 release.

Closes https://github.com/uswitch/kiam/issues/438

### CODE REVIEW

**Comment by stefansedich** [comment]
@pingles will keep this one in draft until ready, I was thinking all v4 related changes could just be rolled into this single PR if you think that works?

**Comment by pingles** [comment]
Do we want to push a version of this with the 4.0-beta2 image?

Or better to just wait to push v4.0 and then this, @Joseph-Irving any thoughts also? (I'm not super familiar with Helm workflows).

**Comment by pingles** [comment]
Am I right in thinking that this means the current Helm chart is broken (given #443)

**Comment by stefansedich** [comment]
> Am I right in thinking that this means the current Helm chart is broken (given #443)

So that looks to be the case pulling the 5.10.0 chart and looking at the contents, my theory here is:

1. #427 was merged making chart changes and not bumping the version
2. CI built and pushed the 5.10.0 chart again with the now breaking changes
3. :cry: 

I would recommend rolling back the chart changes without a version bump so we get a good 5.10.0 pushed again and then rolling the changes into my since PR that adds v4 compatibility with a major version bump.

I am not overly familiar with the CI process but that is what it looks like to me @pingles

**Comment by Joseph-Irving** [comment]
yeah I agree, I think the easiest way to fix the chart is to revert that PR https://github.com/uswitch/kiam/pull/427, which will cause 5.10 to be recreated in a fixed state. We should definitely get that PR back into the helm 6.0 release as it's a breaking change.
I'd probably just wait until we have the 4.0 image @pingles, don't think it's normal to have pre-release images in helm charts generally

**Comment by pingles** [comment]
Thanks @Joseph-Irving. I'd rather not revert that PR if we can avoid it. Can we update the build/Helm charts to fix it also?

**Comment by pingles** [comment]
Or do you mean we just revert the Helm changes that were made as part of that PR?

**Comment by Joseph-Irving** [comment]
yeah just reverting the helm section should fix it, we should make a new PR or incorporate it into this one to reimplement those changes with a version bump

**Comment by stefansedich** [comment]
> yeah just reverting the helm section should fix it, we should make a new PR or incorporate it into this one to reimplement those changes with a version bump

Done I incorporated the `--allow-route-regexp` changes into this PR.

**Comment by pingles** [comment]
Thanks @stefansedich. I've marked as the v4 milestone so should be easier to see what remains now.

**Review by pingles — APPROVED** [review]

**Pull request merged**
