### PR TITLE
Resolve base ARN before checking policy

### PR DESCRIPTION
**Pull request by leosunmo**
This PR ensures that we resolve the role ARN before we check if it's allowed in the Namespace white-list/regex.

Resolves: #326 

This will allow you to use subpaths in the base ARN and match against roles using wildcards without having to include the IAM subpath. More details in original issue.

### CODE REVIEW

**Comment by leosunmo** [comment]
This has been brought in line with Master now. Still working well in my production environment.

**Comment by leosunmo** [comment]
This has once again been brought inline with master. Still running this in my production environment and it's working well.

**Comment by leosunmo** [comment]
@pingles This might be one for v4 as well.

**Comment by pingles** [comment]
Sounds good, thanks! Will take a look.

**Comment by pingles** [comment]
Having a quick look, I wonder whether it makes sense to simplify both policies and for them to only operate on the full resolved role, rather than passing the resolver in as an argument?

It's been a while since I've looked at the rest of the code so not sure of the implications but feels like responsibilities aren't quite right at the moment.

Appreciate it's probably been a while for you too @leosunmo but what do you think?

**Comment by leosunmo** [comment]
I totally agree. Passing the resolver was always the way way out :P I just didn't want to make major changes or spend too much time on it as I wasn't sure if it would be merged. 

With a new release it makes more sense to make some more fundamental changes. I would have to spend some time understanding it first though.

**Comment by pingles** [comment]
Cool. If you don’t get a chance I’ll try and pick it up, thanks for sharing
here though.

**Comment by leosunmo** [comment]
@pingles Has this been incorporated in to https://github.com/uswitch/kiam/pull/435 ?

**Comment by pingles** [comment]
@leosunmo yep! thanks for contributing :-) I made a few changes to fit in with some of the other refactorings I was doing at the time but all good.

**Comment by pingles** [comment]
I'll close this given #435 is merged and had your commits. Thanks again

**Pull request closed without merging**
