### PR TITLE
Support External ID

### LINKED ISSUE #236: External_ID Support for Cross account IAM Role
AWS IAM supports external id as a security measure for cross account IAM roles.
Ref: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html

Issue for enhancement to add support for external id in KIAM.

### PR DESCRIPTION
**Pull request by randomvariable**
Fixes #236 

This supports External ID via annotations as per updated [readme](https://github.com/uswitch/kiam/blob/97c76c3e7e4e300b92de6016a39aa52d3f878cf3/README.md#overview).

### CODE REVIEW

**Comment by pingles** [comment]
Exciting, thanks for working on this @randomvariable

**Comment by harishspqr** [comment]
@pingles Could you please share whats blocking this PR and why the checks have failed ? I am unable to open the details about this failure.

**Comment by randomvariable** [comment]
@harishspqr I hadn't finished it previously, but have done now via the annotations.

Have had a look to see if we could support external ID via a reference to a secret or some other thing.

One of the issues is that if we leveraged a SecretRef, kiam's server would need RBAC permissions to potentially read all secrets in all namespaces, which is less than ideal.

Could get around this by introducing a new CRD, as in this branch: https://github.com/randomvariable/kiam/tree/external-id-crd
([definition](https://github.com/randomvariable/kiam/blob/external-id-crd/config/crds/iam_v1alpha1_iamrole.yaml))

Then kiam can have an RBAC policy to be able to inspect only those CRD types.

The approach in the branch is pretty much that of PodSecurityPolicies - read all the IAM CRDs, find the service account of the pod, and find the first IAM object that passes SubjectAccessReview when ordered alphabetically. To finish that branch, someone would need to continue to rework the interfaces and the cache behaviour to make it work. Potentially a big enough change it should be in a different repository.

That said, this PR is ready in terms of a simple extension via an annotation.

**Comment by harishspqr** [comment]
@randomvariable Awesome! 
Thanks for the details.

**Comment by harishspqr** [comment]
@randomvariable Can we create a secret in a particular namespace and create Role that is limited to the secrets resource in that namespace alone ? Is it possible ?

**Comment by randomvariable** [comment]
@harishspqr Maybe, if it's done as a SecretReference. I probably won't have any time to do anything like that, but if you want to run with it in a separate PR, feel free.

**Comment by danmx** [comment]
@randomvariable are you proposing moving `kiam` towards an operator?

**Comment by randomvariable** [comment]
@pingles @Joseph-Irving I've rebased this on master. Ready for merge.

**Comment by randomvariable** [comment]
Replaced by https://github.com/uswitch/kiam/pull/360

**Pull request closed without merging**
