### PR TITLE
Helm service account annotations and fixes for deployments

### PR DESCRIPTION
**Pull request by tyrken**
* Annotations to allow agent/service service-account annotations
* Fixes for deployment object spec, removing erroneous updateStrategy
* Add (back?) the mount of the host's SSL certs for deployments

I'm using these to work with EKS IAM roles for services accounts... do they look ok?

### CODE REVIEW

**Comment by sbkg0002** [comment]
+1

The current version doesn't work with Helm 3:
```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Deployment.spec): unknown field "updateStrategy" in io.k8s.api.apps.v1.DeploymentSpec
```

**Comment by rhysemmas** [comment]
Thanks for this @tyrken! LGTM, but could you please bump the chart version in `Chart.yaml` so a new chart is packaged when we merge. I believe this would be a minor release, as a backwards-compatible functionality change is being made (alongside the bug fixes)

To expand on the removal of `updateStrategy` from the deployment template for anyone that comes across this PR: the `updateStrategy` field is only valid for daemonsets (which is the default template used when deploying Kiam with Helm).

**Comment by tyrken** [comment]
Rebased & chart version bumped.  Added changelog entry but you'll have to fill in the date when you release.

**Comment by rhysemmas** [comment]
Thanks @tyrken - as an aside, the spaces that were removed in your last commit (your text editor may have done this automatically) are markdown syntax for newlines, so the changelog will render differently now. I will put these back in when the changelog is updated with the date of the chart release

**Comment by tyrken** [comment]
Thanks & sorry about the spaces!

**Pull request merged**
