### PR TITLE
Implement regional STS endpoint support

### LINKED ISSUE #190: Regional STS Endpoint
Does kiam support setting a regional STS endpoint?

It looks like kube2iam supported it and we'd need to be able to set it to be able to use the STS VPC Endpoint.

### PR DESCRIPTION
**Pull request by cjbradfield**
fixes #190

### CODE REVIEW

**Comment by pingles** [comment]
Love it :-)

Only comment would be to maybe add a default/enum to make it easier for operators to understand what value to set in the flag?

**Comment by zytek** [comment]
Will this support aws china regions? I have problem deploying `kiam` on kops-provisioned cluster in aws-cn, and this is possibly cause kiam tries to talk to global aws sts endpoint and not china local.

**Comment by cjbradfield** [comment]
> Love it :-)
> 
> Only comment would be to maybe add a default/enum to make it easier for operators to understand what value to set in the flag?

Sure, I can do that. I'm thinking something like "global-endpoint" as it would be highly unlikely for AWS to use that as a region.

**Comment by cjbradfield** [comment]
> Will this support aws china regions? I have problem deploying `kiam` on kops-provisioned cluster in aws-cn, and this is possibly cause kiam tries to talk to global aws sts endpoint and not china local.

The diff does support regional endpoints in China assuming they exist (I haven't tested there).

**Comment by cjbradfield** [comment]
> Love it :-)
> 
> Only comment would be to maybe add a default/enum to make it easier for operators to understand what value to set in the flag?

Oh wait did you mean replicate all the region list as an enum? Although I see benefit in that, we'd have to constantly edit the list when AWS adds regions which seems error prone. Perhaps I can just add an example to the flag description?

I'm also not a fan of the previous diff I just posted (i'd prefer to leave it the zero value of the string and explain the behavior in the description). I think I misunderstood your feedback.

Anyway, thanks for the opportunity to contribute!

**Comment by pingles** [comment]
Good point, don't want to needlessly replicate the list.

Maybe you could extend the description with a couple of examples so people
can see what kinds of values ought to be accepted?

Additionally, it'd be good to make sure the server exits with a failure if
the user has provided an invalid region for the host- maybe resolve the
address and if it fails to resolve successfully the server process exits
with a failure log message?

**Comment by zytek** [comment]
Could region be auto-discovered from EC2 Metadata / kubernetes labels?

You could also update docs/readme to point out this new feature. 

Gonna check this in `aws-cn` today.

**Comment by zytek** [comment]
I can confirm that `kiam` built from this PR works fine in AWS China. Region autodiscovery would be a nice bonus.

**Comment by cjbradfield** [comment]
> I can confirm that `kiam` built from this PR works fine in AWS China. Region autodiscovery would be a nice bonus.

Hmm. Well, this would get me what I want as-is. I'll add it if everyone agrees it makes the whole thing a lot better.

The only downside I could see is it binds kiam-server to running in-cluster. That may be the case already.

**Comment by zytek** [comment]
> The only downside I could see is it binds kiam-server to running in-cluster. That may be the case already. I also don't know how we would support the fips regions as well (technically, they aren't regions but the Go SDK treats them that way).

I don't think this is a big issue, as when kiam fails to discover region via EC2 Metadata it can fall back to old behavior. Anyway, this can be a scope of another PR. 

Thanks for this submission, it saved my day ;-)

**Comment by pingles** [comment]
It'd be cool to have it auto-discover but I'm also happy for it to default to current behaviour (and add a second for the auto-discovery later). 

Only comment would be if we can add some help docs to the flags to indicate the _kinds_ of values you could set: `eu-west1`, `us-east1` etc. It doesn't have to be exhaustive but useful to give operators an easy way to see the kinds of values they could set.

As I said earlier, other thing I'd like (if possible) would be something that could validate and fail early if someone provides a bad region (typo etc.) as we wouldn't want to start the server, it accept connections and never be able to generate credentials.

**Comment by cjbradfield** [comment]
> It'd be cool to have it auto-discover but I'm also happy for it to default to current behaviour (and add a second for the auto-discovery later).
> 
> Only comment would be if we can add some help docs to the flags to indicate the _kinds_ of values you could set: `eu-west1`, `us-east1` etc. It doesn't have to be exhaustive but useful to give operators an easy way to see the kinds of values they could set.
> 
> As I said earlier, other thing I'd like (if possible) would be something that could validate and fail early if someone provides a bad region (typo etc.) as we wouldn't want to start the server, it accept connections and never be able to generate credentials.

@pingles did you have a chance to look at the updated PR? In it I updated the flag description to include an example and also information about the default behavior.

The regional endpoint is now validated based on the existence of a region as well as DNS resolution of the hostname of the endpoint. In addition, I cache the ResolvedEndpoint so that these checks aren't performed after the initial endpoint resolution.

I have also added a bullet point to the features list in the README.md

Let me know if you want more examples. The tests also will test the resolution of the endpoint. It might be best to make one more change there to make the resolver parametric for testability so that you don't need network connectivity to run the tests.

**Comment by pingles** [comment]
Fantastic, thanks for the contribution!

@Joseph-Irving be great if you guys could cut a release when you can 😄

**Pull request merged**
